sudo: required

dist: trusty

jdk:
  - oraclejdk8 # openJDK crashes sometimes; tensorframes is compiled w.r.t JDK8

cache:
  directories:
    - $HOME/.cache/spark-versions
env:
  matrix:
    - PY_VER=2 SCALA_VERSION=2.11.11 SPARK_VERSION=2.1.1 SPARK_BUILD="spark-${SPARK_VERSION}-bin-hadoop2.7" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz"
    - PY_VER=3 SCALA_VERSION=2.11.11 SPARK_VERSION=2.1.1 SPARK_BUILD="spark-${SPARK_VERSION}-bin-hadoop2.7" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz"

before_install:
 - ./bin/download_travis_dependencies.sh

install:
 - pip2 install --user -r ./python/requirements.txt
 - pip3 install --user -r ./python/requirements.txt

script:
 - SPARK_HOME=$HOME/.cache/spark-versions/$SPARK_BUILD ./bin/testgen.sh
